Repository intel-retail/automated-self-checkout, pull requests merged in 2023-05, with the labels that each got.

#20 fix: sudo required to run docker-build.sh
  docs_src/hardwaresetup.md
Labels: documentation

#23 fix models already exists, exiting... in multiple runs
  modelDownload.sh
Labels: enhancement

#21 fix: docker-build-igt required by benchmark.sh
  docs_src/pipelinebenchmarking.md
Labels: documentation

#27 feat: make default --ocr 5 GPU as value when only specified platform dgpu without --ocr
  get-options.sh
  test_default_dgpu_ocr.sh
Labels: enhancement

#26 Benchmark docker
  Dockerfile.dgpu-dev
  benchmark-scripts/Dockerfile.benchmark
  benchmark-scripts/Dockerfile.igt
  benchmark-scripts/Dockerfile.xpu
  benchmark-scripts/Makefile
  benchmark-scripts/README.md
  benchmark-scripts/benchmark.sh
  benchmark-scripts/cleanup_gpu_metrics.sh
  benchmark-scripts/collect_memory_usage.sh
  benchmark-scripts/collect_platform_metrics.sh
  benchmark-scripts/collect_video_metrics.sh
  benchmark-scripts/collect_video_metrics_flex.sh
  benchmark-scripts/collect_xpum_csv.sh
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
  benchmark-scripts/copy-platform-metrics.sh
  benchmark-scripts/get-gpu-info.sh
  benchmark-scripts/requirements-xpu.txt
  benchmark-scripts/requirements.txt
  benchmark-scripts/stop_platform_collection.sh
  benchmark-scripts/stop_server.sh
  benchmark-scripts/utility_install.sh
  configs/pipelines/xeon/yolov5s_tracking_mixed_cpu_full/pipeline.json
  configs/results/.gitignore
  docker-build-igt.sh
  docker-run-dev.sh
  docker-run-igt.sh
  docker-run.sh
  docs_src/pipelinebenchmarking.md
Labels: enhancement

#28 Fix: UX Improvemenet: USB pipeline help
  docs_src/images/execute_a_dev_video.png
  docs_src/images/list_dev_videos.png
  docs_src/pipelinerun.md
  docs_src/query_usb_camera.md
Labels: documentation

#31 docs: Update release notes for 1.0.0
  docs_src/release-notes/v1-0-0.md
  docs_src/releasenotes.md
Labels: documentation

#35 fix: replace dmesg with the more stable lspci command
  benchmark-scripts/format_avc_mp4.sh
  get-gpu-info.sh
Labels: bug

#33 Release notes
  docs_src/release-notes/v1-0-0.md
Labels: documentation

#37 Docker benchmark
  Dockerfile.dgpu-dev
  benchmark-scripts/Dockerfile.benchmark
  benchmark-scripts/Dockerfile.igt
  benchmark-scripts/Dockerfile.xpu
  benchmark-scripts/Makefile
  benchmark-scripts/README.md
  benchmark-scripts/benchmark.sh
  benchmark-scripts/cleanup_gpu_metrics.sh
  benchmark-scripts/collect_memory_usage.sh
  benchmark-scripts/collect_platform_metrics.sh
  benchmark-scripts/collect_video_metrics.sh
  benchmark-scripts/collect_video_metrics_flex.sh
  benchmark-scripts/collect_xpum_csv.sh
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
  benchmark-scripts/copy-platform-metrics.sh
  benchmark-scripts/get-gpu-info.sh
  benchmark-scripts/requirements-xpu.txt
  benchmark-scripts/requirements.txt
  benchmark-scripts/stop_platform_collection.sh
  benchmark-scripts/stop_server.sh
  benchmark-scripts/utility_install.sh
  configs/pipelines/xeon/yolov5s_tracking_mixed_cpu_full/pipeline.json
  configs/results/.gitignore
  docker-build-igt.sh
  docker-run-dev.sh
  docker-run-igt.sh
  docker-run.sh
  docs_src/benchmark.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinesetup.md
Labels: enhancement

#46 Docs: remove troubleshooting and use FAQ instead
  docs_src/mkdocs.yml
  docs_src/toubleshooting.md
Labels: documentation

#44 docs: update pipeline setup documentation from UX feedback
  .gitignore
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinesetup.md
Labels: documentation

#43 docs: Update platforms to i5 or i7
  docs_src/platforms.md
Labels: documentation

#47 docs: Pipelinerun update
  docs_src/pipelinerun.md
Labels: documentation

#50 Docs: add roadmap document
  docs_src/roadmap.md
Labels: documentation

#45 Docs: update index.md based on UX feedback
  README.md
  docs_src/index.md
  docs_src/mkdocs.yml
Labels: documentation

#49 fix: fixed download_sample_videos.sh should support non dgpu systems
  benchmark-scripts/format_avc_mp4.sh
  benchmark-scripts/test_format_avc_mp4.sh
Labels: bug

#48 Pipeline benchmarking documentation update from UX feedback
  docs_src/benchmark.md
  docs_src/pipelinebenchmarking.md
Labels: documentation

#52 fix: Add missing lspci utility inside benchmark Docker image
  benchmark-scripts/Dockerfile.benchmark
Labels: bug
