Repository intel-retail/automated-self-checkout, pull requests merged in 2023-06, with the labels that each got.

#53 feat: added Makefile for pipeline run
  Makefile
  camera-simulator/camera-simulator.sh
Labels: enhancement

#60 docs: Updated for Makefile added
  Makefile
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
Labels: documentation

#56 feat: Enable pipeline failure log
  configs/dlstreamer/framework-pipelines/arc/yolov5s.sh
  configs/dlstreamer/framework-pipelines/arc/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/arc/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_realsense.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s_full.sh
  docker-run-dlstreamer.sh
  docker-run-opencv-ovms.sh
  docker-run.sh
  docs_src/pipelinerun.md
Labels: enhancement, 1.5.0

#74 Enh: simplify PR template and add issues template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1.5.0

#54 feat: enhance stream density function
  benchmark-scripts/benchmark.sh
  benchmark-scripts/test_stream_density.sh
  configs/dlstreamer/framework-pipelines/stream_density.sh
  docker-run-dlstreamer.sh
  get-options.sh
Labels: enhancement, 1.5.0

#76 feat: enhance the benchmark script to handle --workload option in any argument position
  benchmark-scripts/benchmark.sh
Labels: enhancement, 1.5.0

#81 fix: fix shellcheck script issues
  benchmark-scripts/benchmark.sh
  benchmark-scripts/camera-simulator.sh
  benchmark-scripts/cleanup_gpu_metrics.sh
  benchmark-scripts/copy-platform-metrics.sh
  benchmark-scripts/format_avc_mp4.sh
  benchmark-scripts/get-gpu-info.sh
  benchmark-scripts/log_time_monitor.sh
  benchmark-scripts/run.sh
  benchmark-scripts/run_server.sh
  benchmark-scripts/stop_server.sh
  benchmark-scripts/stream_density.sh
  benchmark-scripts/test_format_avc_mp4.sh
  camera-simulator/camera-simulator.sh
Labels: 1.5.0

#87 fix: fixed docker-run.sh with wrong message when no --workload option
  docker-run.sh
Labels: bug, 1.5.0

#86 feat: Add model download top level script and add unit test for ovms …
  docker-run-dlstreamer.sh
  docker-run-opencv-ovms.sh
  docs_src/pipelinesetup.md
  download_models.sh
  download_models/downloadOVMSModels.sh
  download_models/getModels.sh
  download_models/modelDownload.sh
  download_models/testDownloadOVMSModels.sh
  download_models/testModelDownload.sh
Labels: enhancement, 1.5.0

#80 feat: adding core smoke test
  benchmark-scripts/smoke_test.sh
Labels: enhancement, 1.5.0, 1.0.0

#79 Fix: update collect platform metrics to handle multiple gpu devices
  benchmark-scripts/collect_platform_metrics.sh
Labels: bug, 1.5.0, 1.0.0

#93 Feat: adding core smoke test
  benchmark-scripts/smoke_test.sh
Labels: enhancement, 1.5.0

#94 Fix: update collect platform metrics to handle multiple gpu devices
  benchmark-scripts/collect_platform_metrics.sh
Labels: bug, 1.5.0

#90 Docs: updates for release 1.0.1
  docs_src/camera_serial_number.md
  docs_src/faq.md
  docs_src/hardwaresetup.md
  docs_src/index.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  docs_src/platforms.md
  docs_src/query_usb_camera.md
  docs_src/references.md
  docs_src/release-notes/v1-0-0.md
  docs_src/roadmap.md
Labels: documentation, 1.5.0, 1.0.0

#92 Fix: invert the format avc mp4 script tag logic to match our expected tag
  benchmark-scripts/format_avc_mp4.sh
Labels: bug, 1.5.0, 1.0.0

#95 Fix: invert the format avc mp4 script tag logic to match our expected tag
  benchmark-scripts/format_avc_mp4.sh
Labels: bug, 1.5.0

#97 Docs: updates for release 1.0.1
  docs_src/camera_serial_number.md
  docs_src/faq.md
  docs_src/hardwaresetup.md
  docs_src/index.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  docs_src/platforms.md
  docs_src/query_usb_camera.md
  docs_src/references.md
  docs_src/release-notes/v1-0-0.md
  docs_src/roadmap.md
Labels: documentation, 1.5.0

#106 Fix: pcm directory inconsistent between dockerfile and run script
  benchmark-scripts/Dockerfile.benchmark
  benchmark-scripts/collect_platform_metrics.sh
  benchmark-scripts/get-gpu-info.sh
Labels: bug, 1.0.0

#101 feat: Add cleaning ovms containers to makefile
  Makefile
  clean-containers.sh
Labels: enhancement, 1.5.0

#113 name change
  README.md
  docs_src/index.md
  docs_src/release-notes/v1-0-0.md
Labels: documentation, 1.5.0, 1.0.0

#114 feat: Made CPU as default device for ovms pipeline
  configs/opencv-ovms/models/2022/config.json
Labels: enhancement, 1.5.0

#110 Fix: fix igt log output path in the docker run command
  benchmark-scripts/collect_platform_metrics.sh
Labels: bug, 1.5.0

#117 Docs: github docs code
  Dockerfile.docs
  Makefile
  docs_src/images/logo-white-75px.png
  docs_src/mkdocs.yml
  docs_src/pipelinebenchmarking.md
  docs_src/release-notes/v1-0-1.md
  docs_src/releasenotes.md
  docs_src/stylesheets/branding.css
  docs_src/stylesheets/extra.css
  docs_src/stylesheets/index.css
  mkdocs.yml
Labels: documentation, 1.5.0, 1.0.0

#121 fix: move workflow config files to .github directory
  .github/.rdjson.jq
  .github/.reviewdogConfig.yml
  .github/.trivyConf.yaml
  .github/workflows/reviewdog.yaml
  .github/workflows/trivy-scan.yaml
Labels: 1.5.0

#122 Docs: revert the package name back to implementation
  README.md
  docs_src/index.md
  docs_src/release-notes/v1-0-1.md
Labels: documentation, 1.0.0

#120 fix: fixed pipelinesetup doc has incorrect link to models.list.yml
  docs_src/pipelinesetup.md
Labels: bug, 1.5.0

#116 feat: Added dockerfile.bitModel to download bit models
  Dockerfile.bitModel
  download_models/download_mo_bit_models.sh
Labels: enhancement, 1.5.0

#118 Merge doc changes
  Dockerfile.docs
  Makefile
  docs_src/images/logo-white-75px.png
  docs_src/index.md
  docs_src/mkdocs.yml
  docs_src/pipelinebenchmarking.md
  docs_src/release-notes/v1-0-1.md
  docs_src/releasenotes.md
  docs_src/stylesheets/branding.css
  docs_src/stylesheets/extra.css
  docs_src/stylesheets/index.css
  mkdocs.yml
Labels: documentation, 1.5.0

#125 feat: added OVMS sample image download into run script
  docker-run-opencv-ovms.sh
Labels: enhancement, 1.5.0

#127 docs: update documentation link to github pages
  README.md
Labels: documentation, 1.0.0

#126 docs: Updated doc to include OVMS info
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/pipelinesetup.md
Labels: documentation, 1.5.0

#132 docs: Updated mkdoc to navigate to OVMS docs
  mkdocs.yml
Labels: documentation, 1.5.0

#133 feat: clean up checked-in dlstreamer models
  configs/dlstreamer/models/2022/efficientnet-b0/1/efficientnet-b0.json
  configs/dlstreamer/models/2022/efficientnet-b0/1/imagenet_2012.txt
  configs/dlstreamer/models/2022/horizontal-text-detection-0001/1/horizontal-text-detection-0001.json
  configs/dlstreamer/models/2022/horizontal-text-detection-0002/1/horizontal-text-detection-0002.json
  configs/dlstreamer/models/2022/text-recognition-0012-GPU/1/text-recognition-0012.json
  configs/dlstreamer/models/2022/text-recognition-0014/1/text-recognition-0012.json
  configs/dlstreamer/models/2022/yolov5s/1/yolov5s.json
Labels: 1.5.0, privacy

#137 feat: Add docker image build to workflows
  .github/workflows/build.yaml
  .github/workflows/trivy-scan.yaml
Labels: 1.5.0

#136 feat: add platform and CPU_ONLY parameters to enable smoke testing on all platform types
  benchmark-scripts/smoke_test.sh
Labels: enhancement, 1.5.0

#140 fix: resolve hadolint issues
  .github/.hadolint.yaml
  .github/.reviewdogConfig.yml
  Dockerfile.bitModel
  Dockerfile.dgpu
  Dockerfile.docs
  Dockerfile.ovms-client
  Dockerfile.soc
Labels: 1.5.0

#143 Fix build ovms server make command re-build issue
  Makefile
Labels: bug, 1.5.0

#145 fix: move sample output label to correct location and fix json format
  docs/pipelinerun.html
  docs/sitemap.xml.gz
  docs_src/pipelinerun.md
Labels: documentation, 1.0.0

#147 docs: point model list to github model file
  docs/pipelinesetup.html
  docs/sitemap.xml.gz
  docs_src/pipelinesetup.md
Labels: documentation, 1.0.0

#148 docs: point model list to github model file
  docs_src/pipelinesetup.md
Labels: documentation, 1.5.0

#149 feat: Add performance mode parameter
  benchmark-scripts/benchmark.sh
  docs/pipelinebenchmarking.html
  docs/sitemap.xml.gz
  docs_src/pipelinebenchmarking.md
Labels: enhancement, 1.0.0

#151 fix: update the github workflow from branch 1.5.0 to main branch
  .github/workflows/codeql.yaml
  .github/workflows/trivyimagescan.yaml
Labels: 1.5.0
