Repository intel-retail/automated-self-checkout, pull requests merged in 2023-09, with the labels that each got.

#246 fix: Fixed regex to accept hyphen (-) on ovms model name
  .gitignore
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  configs/opencv-ovms/demos/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py
  configs/opencv-ovms/models/2022/config.json
  configs/opencv-ovms/models/2022/config_template.json
  configs/opencv-ovms/scripts/grpc_python.py
  configs/opencv-ovms/scripts/grpc_python_test.py
  configs/opencv-ovms/scripts/run_grpc_kserv.sh
  configs/opencv-ovms/scripts/run_instance_segmentation.sh
  configs/opencv-ovms/scripts/run_object_detection.sh
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/supportingDifferentModel.md
  download_models/downloadOVMSModels.sh
  download_models/testDownloadOVMSModels.sh
Labels: bug

#248 fix: download standard model ovms name instead of name with _
  download_models/downloadModelsFromList.sh
Labels: bug

#250 fix: mounting gpu device properly without privileged mode
  docker-run-opencv-ovms.sh
  get-options.sh
Labels: bug

#251 feat: generic pipeline configuration
  docker-run-opencv-ovms.sh
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
  download_models/downloadModelsFromList.sh
  download_models/downloadOVMSModels.sh
Labels: enhancement

#253 feat: download models from config_template.json
  .gitignore
  Makefile
  docker-run-opencv-ovms.sh
  download_models/Dockerfile.downloadModels
  download_models/Makefile
  download_models/downloadModelsFromList.sh
  download_models/downloadOVMSModels.sh
  download_models/models.lst
Labels: enhancement

#257 feat: enhance the ovms client infra-structure with the capability to configure env files from /envs directory
  .gitignore
  Makefile
  configs/opencv-ovms/cmd_client/go.mod
  configs/opencv-ovms/cmd_client/go.sum
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/readEnv.go
  configs/opencv-ovms/cmd_client/readEnv_test.go
  configs/opencv-ovms/cmd_client/res/instance_segmentation/configuration.yaml
  configs/opencv-ovms/cmd_client/res/object_detection/configuration.yaml
  configs/opencv-ovms/cmd_client/testdata/empty.env
  configs/opencv-ovms/cmd_client/testdata/test.env
  configs/opencv-ovms/envs/test1.env
  configs/opencv-ovms/envs/test2.env
  docker-run-opencv-ovms.sh
Labels: enhancement

#255 feat: object detection script support configurable env file for model related parameters
  Makefile
  configs/opencv-ovms/cmd_client/res/object_detection/configuration.yaml
  configs/opencv-ovms/demos/object_detection/python/Makefile
  configs/opencv-ovms/envs/object_detection.env
  configs/opencv-ovms/envs/test1.env
  configs/opencv-ovms/envs/test2.env
  configs/opencv-ovms/models/2022/config.json
  configs/opencv-ovms/scripts/run_object_detection.sh
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
  download_models/downloadOVMSModels.sh
  mkdocs.yml
Labels: enhancement

#261 docs: fix the env documentation formatting issue
  docs/404.html
  docs/OVMS/pipelinerun.html
  docs/OVMS/pipelinesetup.html
  docs/OVMS/runObjectDetectionPipelineWithNewModel.html
  docs/OVMS/supportingDifferentLanguage.html
  docs/OVMS/supportingDifferentModel.html
  docs/camera_serial_number.html
  docs/environment_variables.html
  docs/faq.html
  docs/hardwaresetup.html
  docs/index.html
  docs/pipelinebenchmarking.html
  docs/pipelinerun.html
  docs/pipelinesetup.html
  docs/platforms.html
  docs/query_usb_camera.html
  docs/references.html
  docs/release-notes/v1-0-1.html
  docs/release-notes/v1-5-0.html
  docs/releasenotes.html
  docs/roadmap.html
  docs/run_camera_simulator.html
  docs/telemetry/setup.html
  docs_src/environment_variables.md
Labels: bug, documentation

#265 fix: update make-build-docs to use the current user id and group id instead of root user
  Makefile
Labels: enhancement

#269 fix: Remove gst inputsrc string addition for USB cameras
  docker-run-opencv-ovms.sh
Labels: bug, 1.6.0

#270 feat: Update OVMS server to the latest release image instead of the c…
  Makefile
  benchmark-scripts/benchmark.sh
  configs/dlstreamer/extensions/remote_classify.py
  docker-run-opencv-ovms.sh
  docs/OVMS/pipelinerun.html
  docs/OVMS/runObjectDetectionPipelineWithNewModel.html
  docs_src/OVMS/pipelinerun.md
Labels: enhancement, 1.6.0

#274 feat: refactor grpc_python profile and make it run inside docker
  .gitignore
  Makefile
  benchmark-scripts/benchmark.sh
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  configs/opencv-ovms/grpc_python/Dockerfile
  configs/opencv-ovms/grpc_python/Makefile
  configs/opencv-ovms/grpc_python/grpc_postprocess.py
  configs/opencv-ovms/grpc_python/grpc_python.py
  configs/opencv-ovms/grpc_python/grpc_python_test.py
  configs/opencv-ovms/scripts/run_grpc_kserv.sh
  configs/opencv-ovms/scripts/run_grpc_python.sh
  docs_src/OVMS/supportingDifferentModel.md
  run-ovms.sh
Labels: refactor

#275 feat: refactor grpc_go and object_detection profile to use the current profile-launcher
  Makefile
  benchmark-scripts/stream_density.sh
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml
  configs/opencv-ovms/grpc_go/.dockerignore
  configs/opencv-ovms/grpc_go/Makefile
  configs/opencv-ovms/grpc_go/README.md
  configs/opencv-ovms/grpc_go/stream_density_run.sh
  configs/opencv-ovms/scripts/run_grpc_go.sh
  configs/opencv-ovms/scripts/run_object_detection.sh
Labels: refactor

#252 refactor: Replaced person vehicle detection model with ssd mobilenet …
  .gitignore
  configs/opencv-ovms/demos/object_detection/python/labels/coco_80cl_bkgr.txt
  configs/opencv-ovms/envs/object_detection.env
  configs/opencv-ovms/models/2022/config.json
  download_models/downloadModelsFromList.sh
  download_models/downloadOVMSModels.sh
  download_models/models.lst
Labels: refactor

#277 feat: Download public models like the efficientnet classification model
  configs/opencv-ovms/models/2022/config_template.json
  download_models/downloadOVMSModels.sh
Labels: enhancement, question

#281 fix: resolve the gst profile running issue from profile-launcher
  Makefile
  configs/opencv-ovms/scripts/run_gst.sh
Labels: bug
