Repository intel-retail/automated-self-checkout, pull requests merged in 2023-08, with the labels that each got.

#198 feat: Support yolov5s pipeline with grpc_python
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  configs/opencv-ovms/scripts/grpc_postprocess.py
  configs/opencv-ovms/scripts/grpc_python.py
Labels: enhancement, 1.6.0

#199 feat: better error handling for grpc-go while running stream density
  configs/dlstreamer/framework-pipelines/stream_density.sh
  configs/opencv-ovms/grpc_go/main.go
  configs/opencv-ovms/grpc_go/pkg/ovms/inferRequest.go
Labels: enhancement

#200 feat: Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, 1.6.0

#196 Consolidate DLStreamer yolov5s
  configs/dlstreamer/framework-pipelines/xeon/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-cpu.env
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5-gpu.env
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
Labels: enhancement, 1.6.0

#202 feat: enhance stream density cleanup processes logic for better handling cleanup docker process inside a script
  configs/dlstreamer/framework-pipelines/stream_density.sh
Labels: enhancement

#201 feat: Add DLStreamer profile
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/scripts/run_gst.sh
  docker-run-opencv-ovms.sh
Labels: enhancement, 1.6.0

#204 feat: Add clean results folder to makefile clean-all
  Makefile
Labels: enhancement

#209 feat: Python script to modify the model device on run time
  Makefile
  benchmark-scripts/benchmark.sh
  configs/opencv-ovms/models/2022/Dockerfile.updateDevice
  configs/opencv-ovms/models/2022/config_template.json
  configs/opencv-ovms/models/2022/update_server_device.py
  docker-run-opencv-ovms.sh
Labels: enhancement, 1.6.0

#212 feat: Add repo action badges
  .github/workflows/scorecard.yml
  README.md
Labels: enhancement, 1.6.0

#205 refactor: stream density refactor for grpc_go profile
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml
  configs/opencv-ovms/grpc_go/Dockerfile
  configs/opencv-ovms/grpc_go/entrypoint.sh
  configs/opencv-ovms/grpc_go/main.go
  configs/opencv-ovms/grpc_go/stream_density_run.sh
  configs/opencv-ovms/scripts/run_grpc_go.sh
  docker-run-opencv-ovms.sh
Labels: enhancement

#213 fix: resolve the GRPC port issue in the script when number of pipelines is more than 10
  docker-run-opencv-ovms.sh
Labels: bug

#216 fix: add missing clean up for instance segmentation docker container
  Makefile
  docs_src/OVMS/pipelinerun.md
Labels: bug

#219 docs: update doc for OVMS change and benchmarking
  docs_src/OVMS/pipelinerun.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinerun.md
  docs_src/run_camera_simulator.md
Labels: documentation

#221 fix: update the contribution hyperlink in pull request template markdown
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#214 feat: added performance output files to instance segmentation app
  configs/opencv-ovms/instance_segmentation_demo/python/instance_segmentation_demo.py
  configs/opencv-ovms/scripts/run_instance_segmentation.sh
Labels: enhancement

#220 feat: create a make target to list all ovms pipeline profiles
  Makefile
Labels: enhancement

#232 docs: updates to overview & ReadMe pages
  README.md
  docs_src/images/vision-data-flow.jpg
  docs_src/index.md
Labels: documentation

#233 fix: resolve the empty xpum port setting logic issue for Xeon platform
  benchmark-scripts/collect_platform_metrics.sh
Labels: bug

#230 feat: Adding telemetry using influxdb and telegraf
  Makefile
  docs_src/images/dashboard.png
  docs_src/images/import.png
  docs_src/telemetry/setup.md
  mkdocs.yml
  telegraf/Dockerfile
  telegraf/Makefile
  telegraf/docker-run-influxdb.sh
  telegraf/docker-run-telegraf.sh
  telegraf/docker-run.sh
  telegraf/intel_core_and_igpu_telemetry.json
  telegraf/opt/intel-gpu-telegraf/get_intel_gpu_status.sh
  telegraf/opt/intel-gpu-telegraf/telegraf.conf
Labels: documentation, enhancement

#225 docs: add doc for docker-run.sh environment variables
  docs_src/OVMS/pipelinerun.md
  docs_src/environment_variables.md
  docs_src/pipelinerun.md
  mkdocs.yml
Labels: documentation

#236 fix: resolve the issues for pcm-memory in the container
  benchmark-scripts/collect_platform_metrics.sh
Labels: bug

#243 feat: download all models from list and convert them to IR
  docs_src/OVMS/supportingDifferentModel.md
  download_models/Dockerfile.downloadModels
  download_models/Makefile
  download_models/downloadModelsFromList.sh
  download_models/downloadOVMSModels.sh
  download_models/models.lst
Labels: enhancement
