Repository intel-retail/automated-self-checkout, pull requests merged in 2023-11, with the labels that each got.

#333 Add model ready waiting logic to resolve issue #331
  .gitignore
  configs/opencv-ovms/cmd_client/Dockerfile
  configs/opencv-ovms/cmd_client/Dockerfile.unit-test
  configs/opencv-ovms/cmd_client/Makefile
  configs/opencv-ovms/cmd_client/go.mod
  configs/opencv-ovms/cmd_client/go.sum
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/parser/ovmsConfigJsonParser.go
  configs/opencv-ovms/cmd_client/parser/ovmsConfigJsonParser_test.go
  configs/opencv-ovms/cmd_client/parser/test-config_template.json
  configs/opencv-ovms/cmd_client/parser/test-invalid.json
  configs/opencv-ovms/cmd_client/run_unit_test.sh
  configs/opencv-ovms/grpc_go/Dockerfile
  configs/opencv-ovms/grpc_go/go.mod
  configs/opencv-ovms/grpc_go/go.sum
Labels: bug

#334 refactor: Restructure docs for better flow
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/quick_pipelinerun.md
  docs_src/faq.md
  docs_src/hardwaresetup.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  docs_src/pipelinesetup_dlstreamer.md
  docs_src/release-notes/v1-0-1.md
  docs_src/run_camera_simulator.md
  mkdocs.yml
Labels: documentation

#343 docs: add quick start guide documentation for stream density
  Makefile
  docs_src/OVMS/quick_stream_density.md
  mkdocs.yml
Labels: documentation

#342 Fix realsense missing parameters from gst-launch command
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/scripts/run_gst.sh
  get-options.sh
Labels: bug

#349 Adjust gst profile DockerImage accordingly with the input source if RealSense or not
  run-ovms.sh
Labels: enhancement

#344 fix: telegraf image was not working properly
  docs_src/telemetry/setup.md
  telegraf/Dockerfile
  telegraf/docker-run-telegraf.sh
  telegraf/opt/intel-gpu-telegraf/get_intel_gpu_status.sh
Labels: bug

#351 feat: Add latency tracer to the GStreamer pipeline for better perform…
  Dockerfile.dlstreamer
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
Labels: enhancement, 1.6.0

#340 feat: add smoke test for running gst profile with RealSense camera if found
  get-realsense-serialno.sh
  run_smoke_test.sh
Labels: enhancement

#353 feat: enhancement for face detection
  benchmark-scripts/download_sample_videos.sh
  benchmark-scripts/format_avc_mp4.sh
  configs/opencv-ovms/envs/capi_face_detection.env
  configs/opencv-ovms/envs/capi_yolov5.env
  configs/opencv-ovms/envs/classification.env
  configs/opencv-ovms/envs/object_detection.env
  configs/opencv-ovms/gst_capi/launch-pipeline.sh
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
  configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
  configs/opencv-ovms/gst_capi/run_gst_capi.sh
  docs_src/OVMS/capiPipelineRun.md
  docs_src/OVMS/capiYolov5PipelineRun.md
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
Labels: documentation, enhancement, 1.6.0

#355 docs: Adding MQTT instructions and updating influxdb dashboard screen…
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
  docs_src/images/dashboard.png
Labels: documentation

#354 docs: Reorganize docs to create less tabs across the top
  .gitignore
  docs_src/OVMS/pipelinerun.md
  docs_src/environment_variables.md
  docs_src/hardwaresetup.md
  docs_src/index.md
  docs_src/pipelinesetup.md
  docs_src/run_camera_simulator.md
  docs_src/telemetry/setup.md
  mkdocs.yml
Labels: documentation

#356 fix: Detection threshold value check
  configs/opencv-ovms/demos/object_detection/python/object_detection_demo.py
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
  configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
  docs_src/OVMS/capiPipelineRun.md
  docs_src/OVMS/capiYolov5PipelineRun.md
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
Labels: bug, documentation

#360 feat: add text output to capi yolov5 object detected
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
Labels: enhancement, 1.6.0

#362 feat: Each OVMS server has its own config json
  .gitignore
  Makefile
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/server/test-invalid.json
  configs/opencv-ovms/cmd_client/server/test-update-device.json
  configs/opencv-ovms/cmd_client/server/updateDevice.go
  configs/opencv-ovms/cmd_client/server/updateDevice_test.go
  configs/opencv-ovms/models/2022/Dockerfile.updateDevice
  configs/opencv-ovms/models/2022/update_server_device.py
  run-ovms.sh
  test_device_switch.sh
Labels: bug, enhancement

#375 docs: fix make build-ovms-server documentation
  docs_src/OVMS/pipelinesetup.md
Labels: documentation

#377 docs: fix pipeline setup documentation issue about change directory
  docs_src/OVMS/pipelinesetup.md
Labels: documentation

#379 fix: resolve the issue of missing config.json for C-API cases
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/capi_face_detection/configuration.yaml
  configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
  configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
Labels: bug

#384 docs: Update docs
  docs/404.html
  docs/LICENSE.html
  docs/OVMS/capiPipelineRun.html
  docs/OVMS/pipelineDockerCompose.html
  docs/OVMS/pipelinerun.html
  docs/OVMS/pipelinesetup.html
  docs/OVMS/profileLauncherConfigs.html
  docs/OVMS/quick_pipelinerun.html
  docs/OVMS/runObjectDetectionPipelineWithNewModel.html
  docs/OVMS/supportingDifferentLanguage.html
  docs/OVMS/supportingDifferentModel.html
  docs/assets/javascripts/bundle.81fa17fe.min.js
  docs/assets/javascripts/bundle.81fa17fe.min.js.map
  docs/assets/stylesheets/main.4b4a2bd9.min.css
  docs/assets/stylesheets/main.4b4a2bd9.min.css.map
  docs/camera_serial_number.html
  docs/environment_variables.html
  docs/faq.html
  docs/hardwaresetup.html
  docs/images/dashboard.png
  docs/index.html
  docs/pipelinebenchmarking.html
  docs/pipelinerun.html
  docs/pipelinesetup.html
  docs/pipelinesetup_dlstreamer.html
  docs/platforms.html
  docs/query_usb_camera.html
  docs/references.html
  docs/release-notes/v1-0-1.html
  docs/release-notes/v1-5-0.html
  docs/releasenotes.html
  docs/roadmap.html
  docs/run_camera_simulator.html
  docs/search/search_index.json
  docs/telemetry/setup.html
  docs/webcam_rtsp.html
Labels: documentation

#385 docs: update scripts
  docs/OVMS/capiYolov5EnsemblePipelineRun.html
  docs/OVMS/capiYolov5PipelineRun.html
  docs/OVMS/quick_stream_density.html
  docs/assets/javascripts/bundle.cd18aaf1.min.js
  docs/assets/javascripts/bundle.cd18aaf1.min.js.map
  docs/assets/stylesheets/main.fad675c6.min.css
  docs/assets/stylesheets/main.fad675c6.min.css.map
Labels: documentation

#387 feat: enhanced capi yolov5 bounding boxes
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
Labels: enhancement

#389 docs: Adding Barcode env var documentation
  docs_src/OVMS/capiYolov5EnsemblePipelineRun.md
Labels: documentation
