Repository intel-retail/automated-self-checkout, pull requests merged in 2023-12, with the labels that each got.

#390 refactor!: remove --workload parameter from run.sh and deprected --workload dlstreamer run
  Makefile
  README.md
  benchmark-scripts/benchmark.sh
  benchmark-scripts/smoke_test.sh
  benchmark-scripts/smoke_test_benchmark.sh
  configs/opencv-ovms/gst_capi/run_gst_capi.sh
  docs_src/OVMS/capiPipelineRun.md
  docs_src/OVMS/capiYolov5EnsemblePipelineRun.md
  docs_src/OVMS/capiYolov5PipelineRun.md
  docs_src/OVMS/pipelinebenchmarking.md
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/pipelinesetup.md
  docs_src/OVMS/quick_pipelinerun.md
  docs_src/OVMS/quick_stream_density.md
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
  docs_src/OVMS/supportingDifferentLanguage.md
  docs_src/environment_variables.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  docs_src/pipelinesetup_dlstreamer.md
  download_models/downloadModelsFromList.sh
  download_models/downloadOVMSModels.sh
  download_models/getModels.sh
  download_models/models.lst
  get-options.sh
  mkdocs.yml
  run-ovms.sh
  run.sh
  run_smoke_test.sh
  test_device_switch.sh
Labels: refactor, breaking

#393 Clean up leftover dlstreamer code
  .gitignore
  benchmark-scripts/README.md
  benchmark-scripts/benchmark.sh
  benchmark-scripts/stream_density_testcases.sh
  benchmark-scripts/test_format_avc_mp4.sh
  benchmark-scripts/test_streamdensity.sh
  configs/dlstreamer/framework-pipelines/arc/yolov5s.sh
  configs/dlstreamer/framework-pipelines/arc/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/arc/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/core/yolov5s_realsense.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/dgpu/yolov5s_full.sh
  configs/dlstreamer/framework-pipelines/stream_density.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s_effnetb0.sh
  configs/dlstreamer/framework-pipelines/xeon/yolov5s_full.sh
  configs/dlstreamer/models/2022/Horizontal-text-detection-0002_fix.json
  configs/dlstreamer/models/2022/models.list.yml
  configs/dlstreamer/models/2022/yolov5s/1/FP16-INT8/yolov5s.mapping
  configs/dlstreamer/models/2022/yolov5s/1/FP16/yolov5s.mapping
  configs/dlstreamer/models/licenses/APACHE-2.0-TF-Models.txt
  configs/dlstreamer/models/licenses/APACHE-2.0-TF-TPU.txt
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/gst/extensions/OCR_post_processing.py
  configs/opencv-ovms/gst/extensions/OCR_post_processing_0012.py
  configs/opencv-ovms/gst/extensions/barcode.py
  configs/opencv-ovms/gst/extensions/barcode_nv12_to_gray.py
  configs/opencv-ovms/gst/extensions/object_removal_by_label.py
  configs/opencv-ovms/gst/extensions/remote_classify.py
  configs/opencv-ovms/gst/extensions/tracked_object_filter.py
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
  docs_src/OVMS/pipelinesetup.md
  download_models/testModelDownload.sh
  run-dlstreamer.sh
  run-ovms.sh
  run.sh
Labels: refactor, TechDebt

#395 fix: Update xpu manager release
  benchmark-scripts/Dockerfile.xpu
Labels: bug

#396 feat: Capi improvement to choose dGPU to build
  Makefile
  configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst
  configs/opencv-ovms/gst_capi/Makefile
Labels: enhancement, 1.6.0

#404 docs: Adding gif to README
  README.md
  detection.gif
Labels: documentation

#403 fix: resolve the bug of benchmark script when run multiple pipelines with --pipelines 2 or more
  benchmark-scripts/benchmark.sh
  benchmark-scripts/test_benchmark_multiple_pipelines.sh
Labels: bug

#388 docs: update architecture diagram and add description
  docs_src/images/vision-data-flow.jpg
  docs_src/index.md
Labels: documentation

#405 docs: README improvements
  README.md
Labels: documentation

#407 docs: refactor development tools and update architecture diagrams
  docs_src/dev-tools/environment_variables.md
  docs_src/dev-tools/overview.md
  docs_src/dev-tools/references.md
  docs_src/dev-tools/run_camera_simulator.md
  docs_src/dev-tools/telemetry/setup.md
  docs_src/images/automated-checkout-1.0.jpg
  docs_src/images/automated-checkout-1.0.png
  docs_src/images/automated-checkout-ovms.jpg
  docs_src/index.md
  docs_src/troubleshooting.md
  mkdocs.yml
Labels: documentation

#411 fix: making gst yolov5 full work and add PipelineInputAargs
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/envs/yolov5-cpu.env
  configs/opencv-ovms/envs/yolov5-gpu.env
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
  configs/opencv-ovms/scripts/run_gst.sh
  download_models/downloadOVMSModels.sh
Labels: bug, 1.6.0

#415 fix: gst profile env clean up and yolov5s_efficientnet no hardcoded var
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
Labels: bug, enhancement, 1.6.0

#417 docs: faq changes
  docs_src/faq.md
Labels: documentation, TechDebt

#418 feat: yolov5s gst to reuse existing capi yolov5 models
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s.sh
  download_models/downloadOVMSModels.sh
Labels: 1.6.0, TechDebt

#421 fix: Enabling render mode on gst pipelines
  configs/opencv-ovms/envs/yolov5-cpu.env
  configs/opencv-ovms/envs/yolov5-gpu.env
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
  docs_src/dev-tools/environment_variables.md
Labels: bug

#423 docs: fix the missing pipeline profile in the input src table example
  docs_src/OVMS/pipelinerun.md
Labels: documentation

#424 docs: fix the formatting issue for pipeline setup docs page
  docs_src/OVMS/pipelinesetup.md
Labels: documentation

#425 docs: fix the formatting issue of pipeline benchmarking docs page
  docs_src/OVMS/pipelinebenchmarking.md
Labels: documentation
