Repository intel-retail/automated-self-checkout, pull requests merged in 2023-10, with the labels that each got.

#288 fix: fix instance segmentation exiting due to decode issue
  configs/opencv-ovms/demos/classification/python/classification_demo.py
  configs/opencv-ovms/demos/common/python/images_capture.py
  configs/opencv-ovms/demos/instance_segmentation/python/instance_segmentation_demo.py
  configs/opencv-ovms/demos/object_detection/python/object_detection_demo.py
Labels: bug

#290 feat: implementation of single container / client-server through profile-launcher
  .gitignore
  Makefile
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/readEnv.go
  configs/opencv-ovms/cmd_client/readEnv_test.go
  configs/opencv-ovms/cmd_client/res/classification/configuration.yaml
  configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/cmd_client/res/instance_segmentation/configuration.yaml
  configs/opencv-ovms/cmd_client/res/object_detection/configuration.yaml
  configs/opencv-ovms/cmd_client/res/test/configuration.yaml
  configs/opencv-ovms/envs/ovms_server.env
  configs/opencv-ovms/scripts/start_ovms_server.sh
  run-ovms.sh
  run_smoke_test.sh
Labels: enhancement

#304 refact: changed docker image to convert sample videos
  benchmark-scripts/format_avc_mp4.sh
Labels: enhancement

#305 docs: Updating README for a QuickStart
  README.md
Labels: documentation

#307 docs: Update note format to use pymdownx.details, add footer
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/pipelinesetup.md
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
  docs_src/OVMS/supportingDifferentLanguage.md
  docs_src/OVMS/supportingDifferentModel.md
  docs_src/camera_serial_number.md
  docs_src/hardwaresetup.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  docs_src/query_usb_camera.md
  docs_src/run_camera_simulator.md
  docs_src/webcam_rtsp.md
  mkdocs.yml
Labels: documentation

#301 feat: Refactor inputsrc and remove INPUTSRC_TYPE from ovms
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/demos/classification/python/entrypoint.sh
  configs/opencv-ovms/demos/instance_segmentation/python/entrypoint.sh
  configs/opencv-ovms/demos/object_detection/python/entrypoint.sh
  configs/opencv-ovms/envs/yolov5-cpu.env
  configs/opencv-ovms/envs/yolov5-gpu.env
  configs/opencv-ovms/grpc_go/entrypoint.sh
  configs/opencv-ovms/scripts/run_classification.sh
  configs/opencv-ovms/scripts/run_grpc_go.sh
  configs/opencv-ovms/scripts/run_grpc_python.sh
  configs/opencv-ovms/scripts/run_gst.sh
  configs/opencv-ovms/scripts/run_instance_segmentation.sh
  configs/opencv-ovms/scripts/run_object_detection.sh
  create-symbolic-link.sh
  run-ovms.sh
  run_smoke_test.sh
Labels: enhancement

#308 feat: add profile gst_capi face_detection
  Makefile
  benchmark-scripts/download_sample_videos.sh
  configs/opencv-ovms/cmd_client/res/face_detection/configuration.yaml
  configs/opencv-ovms/envs/face_detection.env
  configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst
  configs/opencv-ovms/gst_capi/Makefile
  configs/opencv-ovms/gst_capi/launch-pipeline.sh
  configs/opencv-ovms/gst_capi/pipelines/build-demos.sh
  configs/opencv-ovms/gst_capi/pipelines/face_detection/Makefile
  configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
  configs/opencv-ovms/models/2022/config_template.json
  configs/opencv-ovms/scripts/run_face_detection.sh
  download_models/getModels.sh
  run-ovms.sh
Labels: enhancement, 1.6.0

#302 Expand profile-launcher configs to support the generic docker-run script
  .gitignore
  Makefile
  benchmark-scripts/stream_density.sh
  configs/dlstreamer/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/classification/configuration.yaml
  configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/cmd_client/res/instance_segmentation/configuration.yaml
  configs/opencv-ovms/cmd_client/res/object_detection/configuration.yaml
  configs/opencv-ovms/cmd_client/res/test/configuration.yaml
  configs/opencv-ovms/cmd_client/writeEnv.go
  configs/opencv-ovms/cmd_client/writeEnv_test.go
  configs/opencv-ovms/demos/classification/python/entrypoint.sh
  configs/opencv-ovms/demos/instance_segmentation/python/entrypoint.sh
  configs/opencv-ovms/demos/object_detection/python/entrypoint.sh
  configs/opencv-ovms/envs/classification.env
  configs/opencv-ovms/envs/grpc_python.env
  configs/opencv-ovms/envs/gst.env
  configs/opencv-ovms/envs/object_detection.env
  configs/opencv-ovms/envs/yolov5-cpu.env
  configs/opencv-ovms/envs/yolov5-gpu.env
  configs/opencv-ovms/grpc_python/run_grpc_python.sh
  configs/opencv-ovms/scripts/docker-launcher.sh
  configs/opencv-ovms/scripts/run_classification.sh
  configs/opencv-ovms/scripts/run_grpc_go.sh
  configs/opencv-ovms/scripts/run_gst.sh
  configs/opencv-ovms/scripts/run_instance_segmentation.sh
  configs/opencv-ovms/scripts/run_object_detection.sh
Labels: enhancement

#310 feat: Simplify DLStreamer image to use a common image
  .github/workflows/trivyimagescan.yaml
  Dockerfile.dgpu
  Dockerfile.dlstreamer
  Makefile
  benchmark-scripts/test_format_avc_mp4.sh
  configs/opencv-ovms/cmd_client/res/gst/configuration.yaml
  configs/opencv-ovms/scripts/run_gst.sh
  docker-build.sh
  docs/camera_serial_number.html
  docs/pipelinerun.html
  docs/pipelinesetup.html
  docs_src/camera_serial_number.md
  docs_src/pipelinerun.md
  docs_src/pipelinesetup.md
  run-dlstreamer.sh
Labels: enhancement, 1.6.0

#312 feat: create gst capi results log files and integration with docker launch
  Makefile
  configs/opencv-ovms/cmd_client/res/capi_face_detection/configuration.yaml
  configs/opencv-ovms/cmd_client/res/face_detection/configuration.yaml
  configs/opencv-ovms/envs/capi_face_detection.env
  configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst
  configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
  configs/opencv-ovms/gst_capi/run_face_detection.sh
  configs/opencv-ovms/scripts/docker-launcher.sh
  run_smoke_test.sh
Labels: enhancement, 1.6.0

#314 docs: add documentation for profile launcher configuration
  docs_src/OVMS/pipelinesetup.md
  docs_src/OVMS/profileLauncherConfigs.md
Labels: documentation

#315 docs: add gst capi face detection documentation
  configs/opencv-ovms/envs/capi_face_detection.env
  docs_src/OVMS/capiPipelineRun.md
  mkdocs.yml
Labels: documentation, 1.6.0

#318 feat: add hadolint Docker makefile target for developers used locally
  Makefile
  telegraf/Dockerfile
Labels: enhancement

#319 feat: update object detection model and docs
  .gitignore
  configs/opencv-ovms/demos/object_detection/python/labels/person_vehicle_bike_detection_2000.txt
  configs/opencv-ovms/models/2022/config_template.json
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
Labels: documentation, enhancement, 1.6.0

#317 feat: enhance getting realsense camera serial number into a script and makefile target
  Makefile
  docs_src/camera_serial_number.md
  get-realsense-serialno.sh
Labels: enhancement

#327 feat: download ovms models to requested precision only
  download_models/downloadOVMSModels.sh
Labels: enhancement, 1.6.0

#320 fix: missing containername env variable
  configs/opencv-ovms/demos/instance_segmentation/python/instance_segmentation_demo.py
  configs/opencv-ovms/scripts/docker-launcher.sh
Labels: bug

#330 refactor: Rework numbering in docs and add License
  docs_src/LICENSE.md
  docs_src/OVMS/pipelinesetup.md
  docs_src/hardwaresetup.md
  docs_src/index.md
  docs_src/pipelinebenchmarking.md
  docs_src/pipelinesetup.md
  docs_src/query_usb_camera.md
Labels: documentation, enhancement, refactor

#329 feat: refactor the way for the value of cid_count env and GRPC_PORT env
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/ovmsClientConf_test.go
  configs/opencv-ovms/cmd_client/ovmsGrpcPort.go
  configs/opencv-ovms/cmd_client/portfinder/findPort.go
  configs/opencv-ovms/cmd_client/portfinder/findPort_test.go
  configs/opencv-ovms/scripts/get_server_grpc_port.sh
  run-ovms.sh
  run_smoke_test.sh
Labels: refactor, TechDebt
