Repository intel-retail/automated-self-checkout, pull requests merged in 2023-07, with the labels that each got.

#152 feat: Add performance mode parameter
  benchmark-scripts/benchmark.sh
  docs_src/pipelinebenchmarking.md
Labels: enhancement, 1.5.0

#159 fix: change github action build to be on demand
  .github/workflows/build.yaml
Labels: 1.5.0

#144 feat: Add OVMS client script into go main configuration
  .gitignore
  Dockerfile.ovms-client
  configs/opencv-ovms/cmd_client/go.mod
  configs/opencv-ovms/cmd_client/go.sum
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/configuration.yaml
  configs/opencv-ovms/scripts/grpc_infer_binary_maskrcnn-omz.py
  docker-run-opencv-ovms.sh
Labels: enhancement, 1.6.0

#161 fix: Resolve syntax error for trivy image scan workflow
  .github/workflows/trivyimagescan.yaml
Labels: 1.5.0

#163 feat: Add workflow creates security related reports
  .github/.trivyConf.yaml
  .github/workflows/reports.yaml
  .github/workflows/trivy-scan.yaml
Labels: 1.5.0

#171 feat: add BIT_model downloader and update the configuration to run it
  .gitignore
  configs/opencv-ovms/cmd_client/res/configuration.yaml
  configs/opencv-ovms/scripts/grpc_python.py
  configs/opencv-ovms/scripts/run_grpc_kserv.sh
  docs_src/OVMS/pipelinesetup.md
  download_models/downloadOVMSModels.sh
  download_models/download_mo_bit_models.sh
Labels: enhancement

#173 feat: implement pipeline profile for opencv-ovms runs
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml
  docker-run-opencv-ovms.sh
Labels: enhancement

#175 fix: Add dataset disclaimer
  README.md
Labels: documentation

#178 docs: Add dataset disclaimer
  README.md
Labels: documentation, 1.5.0

#184 Fix ovms client cleanup grpc go
  Makefile
  docs_src/OVMS/pipelinerun.md
Labels: bug

#186 fix: resolve the ovms model downloader issue
  download_models/downloadOVMSModels.sh
Labels: bug

#188 fix: Resolve the issue of OVMS stream density mode for grpc_python pipeline profile
  benchmark-scripts/benchmark.sh
  configs/dlstreamer/framework-pipelines/stream_density.sh
  configs/opencv-ovms/cmd_client/main.go
Labels: bug

#189 feat: output FPS for go pipeline
  configs/opencv-ovms/grpc_go/Dockerfile
  configs/opencv-ovms/grpc_go/entrypoint.sh
  configs/opencv-ovms/grpc_go/main.go
  configs/opencv-ovms/scripts/run_grpc_go.sh
Labels: enhancement

#193 fix: resolve the issue of running multiple instances of grpc-go pipelines
  configs/opencv-ovms/grpc_go/entrypoint.sh
  configs/opencv-ovms/scripts/run_grpc_go.sh
Labels: bug

#195 fix: correct the fps calculation in grpc_go
  configs/opencv-ovms/grpc_go/main.go
Labels: bug
