Repository intel-retail/automated-self-checkout, pull requests merged in 2024-01, with the labels that each got.

#432 feat: update docker version + container logs
  configs/opencv-ovms/demos/classification/python/entrypoint.sh
  configs/opencv-ovms/demos/instance_segmentation/python/entrypoint.sh
  configs/opencv-ovms/demos/object_detection/python/entrypoint.sh
  configs/opencv-ovms/grpc_go/entrypoint.sh
  docs_src/hardwaresetup.md
Labels: documentation, TechDebt

#436 fix: docker compose up failed with "Error: configuration file not found or cannot open"
  Makefile
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/models/2022/config_template.json
  configs/opencv-ovms/scripts/gen_ovms_model_config_json.sh
  docker-compose.yml
Labels: bug, 1.6.0, TechDebt

#433 fix: classification profile to use efficientnetb0_FP32INT8 config model
  configs/opencv-ovms/envs/classification.env
  configs/opencv-ovms/models/2022/config_template.json
  docker-compose.yml
  docs_src/OVMS/capiYolov5EnsemblePipelineRun.md
Labels: 1.6.0

#435 feat: add run cached demo
  Makefile
Labels: enhancement

#439 fix: make clean-all has error if the first time or without running docker-compose
  Makefile
Labels: bug, 1.6.0, TechDebt

#438 feat: add gst classification smoke test
  run_smoke_test.sh
Labels: enhancement

#445 fix: update the xpu requirement.txt for benchmark docker image built
  benchmark-scripts/requirements-xpu.txt
Labels: bug, 2.0

#448 docs: Add anchoring for navigation and toc
  mkdocs.yml
Labels: documentation

#443 docs: add documentation for changing model precision while running on device GPU
  docs_src/OVMS/quick_stream_density.md
  docs_src/troubleshooting.md
Labels: documentation, 2.0

#449 feat: add smoke tests for running on device GPU
  run_smoke_test.sh
Labels: 2.0

#452 docs: Remove choose pipeline page
  docs_src/hardwaresetup.md
  docs_src/pipelinesetup.md
  mkdocs.yml
Labels: 2.0

#450 docs: Re-organize OVMS Run Pipeline section
  docs_src/OVMS/pipelinerun.md
  docs_src/OVMS/stop_pipeline_run.md
  docs_src/OVMS/supportingDifferentLanguage.md
  docs_src/OVMS/supportingDifferentModel.md
  docs_src/dev-tools/run_camera_simulator.md
  mkdocs.yml
Labels: documentation, 2.0

#454 docs: clean up environment variables page to remove DLStreamer refs
  docs_src/dev-tools/environment_variables.md
Labels: documentation, 2.0

#455 docs: Add code copy buttons
  mkdocs.yml
Labels: documentation, 2.0

#453 feat: add integration test github workflow action
  .github/workflows/integration.yaml
  benchmark-scripts/download_sample_videos.sh
  benchmark-scripts/format_avc_mp4.sh
  docs_src/OVMS/pipelinesetup.md
  download_models/downloadOVMSModels.sh
  get-realsense-serialno.sh
  run_smoke_test.sh
Labels: enhancement, 2.0

#460 docs: added mike
  docs/404.html
  docs/LICENSE.html
  docs/OVMS/capiPipelineRun.html
  docs/OVMS/capiYolov5EnsemblePipelineRun.html
  docs/OVMS/capiYolov5PipelineRun.html
  docs/OVMS/pipelineDockerCompose.html
  docs/OVMS/pipelinerun.html
  docs/OVMS/pipelinesetup.html
  docs/OVMS/profileLauncherConfigs.html
  docs/OVMS/quick_pipelinerun.html
  docs/OVMS/quick_stream_density.html
  docs/OVMS/runObjectDetectionPipelineWithNewModel.html
  docs/OVMS/supportingDifferentLanguage.html
  docs/OVMS/supportingDifferentModel.html
  docs/assets/javascripts/bundle.cd18aaf1.min.js
  docs/assets/javascripts/bundle.cd18aaf1.min.js.map
  docs/assets/javascripts/lunr/min/lunr.ar.min.js
  docs/assets/javascripts/lunr/min/lunr.el.min.js
  docs/assets/javascripts/lunr/min/lunr.he.min.js
  docs/assets/javascripts/lunr/min/lunr.hy.min.js
  docs/assets/javascripts/lunr/min/lunr.kn.min.js
  docs/assets/javascripts/lunr/min/lunr.ko.min.js
  docs/assets/javascripts/lunr/min/lunr.sa.min.js
  docs/assets/javascripts/lunr/min/lunr.ta.min.js
  docs/assets/javascripts/lunr/min/lunr.te.min.js
  docs/assets/javascripts/lunr/min/lunr.zh.min.js
  docs/assets/javascripts/lunr/wordcut.js
  docs/assets/javascripts/workers/search.f886a092.min.js
  docs/assets/javascripts/workers/search.f886a092.min.js.map
  docs/assets/stylesheets/main.fad675c6.min.css
  docs/assets/stylesheets/main.fad675c6.min.css.map
  docs/assets/stylesheets/palette.356b1318.min.css
  docs/assets/stylesheets/palette.356b1318.min.css.map
  docs/camera_serial_number.html
  docs/environment_variables.html
  docs/faq.html
  docs/hardwaresetup.html
  docs/images/automated-checkout-1.0.png
  docs/images/vision-data-flow.jpg
  docs/index.html
  docs/pipelinebenchmarking.html
  docs/pipelinerun.html
  docs/pipelinesetup.html
  docs/pipelinesetup_dlstreamer.html
  docs/platforms.html
  docs/query_usb_camera.html
  docs/references.html
  docs/release-notes/v1-0-1.html
  docs/release-notes/v1-5-0.html
  docs/releasenotes.html
  docs/roadmap.html
  docs/run_camera_simulator.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/telemetry/setup.html
  docs/webcam_rtsp.html
  mkdocs.yml
Labels: documentation

#461 feat: Add integration test tag for the main repo
  README.md
Labels: enhancement, 2.0

#457 fix: Restore GST env vars
  docs_src/dev-tools/environment_variables.md
Labels: documentation, 2.0

#463 docs: fix the formatting json issue of troubleshooting page
  docs_src/troubleshooting.md
Labels: documentation, 2.0

#466 doc: support documentation versioning via mike tool
  .github/workflows/gh-pages.yml
  docs/OVMS/pipelinesetup.html
  docs/faq.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs_src/dev-tools/documentation.md
  docs_src/faq.md
  docs_src/hardwaresetup.md
  docs_src/images/documentation-version-dropdown.png
  mkdocs.yml
Labels: documentation, TechDebt, 2.0

#467 docs: Fix code comment blocks to make it easier to read
  docs_src/OVMS/camera_serial_number.md
  docs_src/OVMS/capiPipelineRun.md
  docs_src/OVMS/pipelineDockerCompose.md
  docs_src/OVMS/pipelinebenchmarking.md
  docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
Labels: documentation, 2.0

#469 fix: use GPU on DEVICE env to test on serpent canyon
  run_smoke_test.sh
Labels: TechDebt, 2.0

#475 fix: Updating GPU utilization field for DGPU
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
Labels: bug, 2.0

#476 fix: swaping igt filename to align with GPU.0 or GPU.1
  benchmark-scripts/collect_platform_metrics.sh
  docs_src/OVMS/pipelinebenchmarking.md
  docs_src/OVMS/quick_stream_density.md
  docs_src/dev-tools/environment_variables.md
Labels: bug

#478 fix: dependabot updates
  benchmark-scripts/requirements-xpu.txt
  benchmark-scripts/requirements.txt
  requirements.txt
Labels: dependencies, 2.0
