Repository intel-retail/automated-self-checkout, pull requests merged in 2024-08, with the labels that each got.

#604 fix: have non helm version use local sample video when available
  Makefile
  helm/Dockerfile.cam-sim
  helm/Makefile
  helm/docker-compose.yml
  helm/kubernetes.md
  helm/swarm.md
  src/docker-compose.yml
  src/pipeline-server/docker-compose.pipeline-server.yml
  src/pipeline-server/postman/env.json
  src/pipeline-server/postman/pipeline.json
  src/pipeline-server/run-pipelines.sh
Labels: breaking, 3.1

#603 feat: Independent Docker image for low code (DLStreamer) version of the microservice
  helm/Dockerfile
  helm/docker-compose.yml
  helm/requirements.txt
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/pipelines/yolov5s_full.sh
Labels: enhancement, 3.1

#611 fix: dependabot update opencv-python
  src/pipeline-server/requirements.txt
  src/requirements.txt
Labels: dependencies

#613 feat: update dlstreamer to use 2024.1 image
  helm/Dockerfile
  src/Dockerfile
Labels: dependencies

#616 fix: revert as casing in dockerfile to resolve codeql vuln
  helm/Dockerfile
  src/Dockerfile
Labels: dependencies

#617 fix: Revert the servers to the proper image
  src/pipeline-server/docker-compose.pipeline-server.yml
Labels: bug, 3.1
