Repository intel-retail/automated-self-checkout, pull requests merged in 2024-06, with the labels that each got.

#574 fix: Output file names to match latest yolo pipeline
  src/pipelines/yolov5s_effnetb0.sh
  src/pipelines/yolov5s_full.sh
Labels: bug, 3.1

#575 feat: Add env file for CPU, GPU, and mixed configurations for the efficientnet pipeline
  Makefile
  src/benchmark-commands.md
  src/docker-compose.yml
  src/pipelines/yolov5s_effnetb0.sh
  src/res/all-cpu.env
  src/res/all-gpu.env
  src/res/yolov5-cpu-class-gpu.env
  src/res/yolov5-gpu-class-cpu.env
Labels: enhancement, 3.1

#576 feat: Add headless version of run-demo
  Makefile
  src/docker-compose.yml
Labels: enhancement, 3.1

#579 fix: Revert network back to localhost
  src/docker-compose.yml
Labels: bug, breaking, 3.1

#581 feat: Kubernetes support to Automated Self Checkout
  .deploy/object-detection-service-low-code-3.0.0.tgz
  .gitignore
  Makefile
  helm/Chart.yaml
  helm/Dockerfile
  helm/Dockerfile.cam-sim
  helm/Makefile
  helm/docker-compose.yml
  helm/kubernetes.md
  helm/yolov5-cpu.env
  index.yaml
  object-detection-service-low-code-3.0.0.tgz
  src/res/gst.env
Labels: enhancement, 3.1

#591 Adding docker swarm support
  helm/Makefile
  helm/docker-compose.yml
  helm/swarm.md
Labels: enhancement
