Repository intel-retail/automated-self-checkout, pull requests merged in 2024-05, with the labels that each got.

#561 fix: Default parameters and update documents
  Makefile
  README.md
  docs/404.html
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs_src/advanced.md
  docs_src/getting_started.md
  docs_src/performance.md
  smoke_test.sh
  src/docker-compose.yml
  src/entrypoint.sh
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/pipelines/yolov5s_full.sh
  src/res/gst.env
  src/res/yolov5-cpu.env
  src/res/yolov5-gpu.env
Labels: enhancement, 3.0

#566 doc: Move github pages to the documentation repo
  README.md
  docs/404.html
  docs/assets/images/favicon.png
  docs/assets/javascripts/lunr/min/lunr.ar.min.js
  docs/assets/javascripts/lunr/min/lunr.da.min.js
  docs/assets/javascripts/lunr/min/lunr.de.min.js
  docs/assets/javascripts/lunr/min/lunr.du.min.js
  docs/assets/javascripts/lunr/min/lunr.es.min.js
  docs/assets/javascripts/lunr/min/lunr.fi.min.js
  docs/assets/javascripts/lunr/min/lunr.fr.min.js
  docs/assets/javascripts/lunr/min/lunr.hi.min.js
  docs/assets/javascripts/lunr/min/lunr.hu.min.js
  docs/assets/javascripts/lunr/min/lunr.it.min.js
  docs/assets/javascripts/lunr/min/lunr.ja.min.js
  docs/assets/javascripts/lunr/min/lunr.jp.min.js
  docs/assets/javascripts/lunr/min/lunr.multi.min.js
  docs/assets/javascripts/lunr/min/lunr.nl.min.js
  docs/assets/javascripts/lunr/min/lunr.no.min.js
  docs/assets/javascripts/lunr/min/lunr.pt.min.js
  docs/assets/javascripts/lunr/min/lunr.ro.min.js
  docs/assets/javascripts/lunr/min/lunr.ru.min.js
  docs/assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  docs/assets/javascripts/lunr/min/lunr.sv.min.js
  docs/assets/javascripts/lunr/min/lunr.th.min.js
  docs/assets/javascripts/lunr/min/lunr.tr.min.js
  docs/assets/javascripts/lunr/min/lunr.vi.min.js
  docs/assets/javascripts/lunr/min/lunr.zh.min.js
  docs/assets/javascripts/lunr/tinyseg.js
  docs/assets/javascripts/lunr/wordcut.js
  docs/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs_src/LICENSE.md
  docs_src/advanced.md
  docs_src/getting_started.md
  docs_src/images/execute_a_dev_video.png
  docs_src/images/list_dev_videos.png
  docs_src/images/logo-white-75px.png
  docs_src/images/vision-data-flow.jpg
  docs_src/index.md
  docs_src/performance.md
  docs_src/stylesheets/branding.css
  docs_src/stylesheets/extra.css
  docs_src/stylesheets/index.css
Labels: documentation, 3.0

#570 feat: Added automated checkout notebook
  .gitignore
  notebooks/Dockerfile
  notebooks/README.md
  notebooks/automated-checkout.ipynb
  notebooks/output.jpg
Labels: enhancement

#569 fix: Remove unused build step from camera simulator
  src/docker-compose.yml
Labels: bug, 3.1
