Repository intel-retail/automated-self-checkout, pull requests merged in 2024-02, with the labels that each got.

#477 feat: Release notes for release 2.0
  docs/404.html
  docs/LICENSE.html
  docs/OVMS/capiPipelineRun.html
  docs/OVMS/capiYolov5EnsemblePipelineRun.html
  docs/OVMS/capiYolov5PipelineRun.html
  docs/OVMS/pipelineDockerCompose.html
  docs/OVMS/pipelinerun.html
  docs/OVMS/pipelinesetup.html
  docs/OVMS/profileLauncherConfigs.html
  docs/OVMS/quick_pipelinerun.html
  docs/OVMS/quick_stream_density.html
  docs/OVMS/runObjectDetectionPipelineWithNewModel.html
  docs/OVMS/supportingDifferentLanguage.html
  docs/OVMS/supportingDifferentModel.html
  docs/assets/javascripts/lunr/min/lunr.ar.min.js
  docs/assets/javascripts/lunr/min/lunr.zh.min.js
  docs/assets/javascripts/lunr/wordcut.js
  docs/faq.html
  docs/hardwaresetup.html
  docs/index.html
  docs/platforms.html
  docs/query_usb_camera.html
  docs/release-notes/v1-0-1.html
  docs/release-notes/v1-5-0.html
  docs/releasenotes.html
  docs/roadmap.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/webcam_rtsp.html
  docs_src/release-notes/v2-0-0.md
  docs_src/releasenotes.md
  mkdocs.yml
Labels: documentation, 2.0

#483 feat: Add indexing to camera simulator videos
  benchmark-scripts/download_sample_videos.sh
  benchmark-scripts/format_avc_mp4.sh
  docs_src/dev-tools/run_camera_simulator.md
Labels: documentation, enhancement, 2.1

#484 refactor: ovms model download scripts refactor and cleanup
  download_models/downloadOVMSModels.sh
  download_models/modelDownload.sh
  download_models/testDownloadOVMSModels.sh
Labels: refactor, TechDebt, 2.1

#487 fix: Add indexes to docker compose for camera simulators
  docker-compose-cam.yml
  docker-compose.yml
Labels: enhancement, 2.1

#489 doc: update on mike tool
  docs_src/dev-tools/documentation.md
Labels: documentation

#494 fix: docs versioning bug
  mkdocs.yml
Labels: 2.1

#493 feat: parameterize batch-size in gst pipelines via environment variable
  configs/opencv-ovms/envs/gst.env
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_effnetb0.sh
  configs/opencv-ovms/gst/framework-pipelines/yolov5_pipeline/yolov5s_full.sh
  configs/opencv-ovms/scripts/run_gst.sh
  docs_src/dev-tools/environment_variables.md
Labels: enhancement, 2.1

#496 Discord link
  README.md
Labels: documentation, 2.1

#497 docs: Update arc instructions, add troubleshooting
  docs_src/hardwaresetup.md
  docs_src/troubleshooting.md
Labels: documentation, 2.1

#501 Add capi yolov8 ensemble pipeline profile
  .gitignore
  Makefile
  configs/opencv-ovms/cmd_client/main.go
  configs/opencv-ovms/cmd_client/res/capi_yolov8_ensemble/configuration.yaml
  configs/opencv-ovms/cmd_client/res/capi_yolov8_ensemble/yolov8_custom_node.json
  configs/opencv-ovms/cmd_client/server/customNode.go
  configs/opencv-ovms/cmd_client/server/customNode_test.go
  configs/opencv-ovms/cmd_client/server/test-yolov8_custom_node.json
  configs/opencv-ovms/envs/capi_yolov8_ensemble.env
  configs/opencv-ovms/gst_capi/Dockerfile.ovms.yolov8
  configs/opencv-ovms/gst_capi/Makefile
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/Makefile
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/buffersqueue.cpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/buffersqueue.hpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_interface.h
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_library_internal_manager.cpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_library_internal_manager.hpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/efficientnetb0_node.cpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/efficientnetb0_node_debug.cpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/main.cpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/opencv_utils.hpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/queue.hpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/utils.hpp
  configs/opencv-ovms/gst_capi/pipelines/capi_yolov8_ensemble/yolo_efficientnet.sh
  configs/opencv-ovms/models/2022/config_template.json
  configs/opencv-ovms/scripts/docker-launcher.sh
  docs_src/OVMS/capiYolov8EnsemblePipelineRun.md
  download_models/Dockerfile.yolov8-download
  download_models/downloadOVMSModels.sh
  download_models/model_build/convert-model.py
  download_models/model_build/convert-model.sh
  download_models/model_build/download-tools.sh
  download_models/model_build/quantize-model.py
  run_smoke_test.sh
Labels: enhancement, 2.1

#504 fix: gh-actions for doc versioning
  .github/workflows/gh-pages.yml
Labels: bug, TechDebt

#510 fix: update go.mod net version to fix several high security vulnerability
  configs/opencv-ovms/cmd_client/go.mod
Labels: dependencies, 2.1

#511 doc: Release notes for 2.1
  docs_src/release-notes/v2-1-0.md
Labels: documentation, 2.1
