Repository intel-retail/automated-self-checkout, pull requests merged in 2025-03, with the labels that each got.

#668 fix: scorecard issues for sdle
  .github/workflows/reviewdog.yaml
  src/common-service/Dockerfile
  src/common-service/requirements.txt
  src/retail-data-visualization/Dockerfile.grafana
  src/retail-data-visualization/Dockerfile.retail-data-visualization
Labels: security

#674 fix: scorecard issues, add hash for packages
  .github/workflows/requirements.txt
  .github/workflows/reviewdog.yaml
  smoke_test.sh
  src/common-service/Dockerfile
  src/common-service/requirements.txt
  src/retail-data-visualization/Dockerfile.retail-data-visualization
  src/retail-data-visualization/requirements.txt
Labels: security

#687 fix: security issue with jinja pkg
  src/retail-data-visualization/requirements.txt
Labels: security

#680 refactor: set batch size from env variable
  src/benchmark-commands.md
  src/docker-compose.yml
  src/pipelines/yolov5s_effnetb0.sh
Labels: refactor, oss_hackathon

#675 refactor: update dlstreamer version
  src/Dockerfile
Labels: oss_hackathon

#667 bug: add file yolov5-gpu.env
  src/res/yolov5-gpu.env
Labels: bug, oss_hackathon

#690 Improve detection and classification pipelines
  Makefile
  README.md
  benchmark-commands.md
  src/.env
  src/Dockerfile
  src/docker-compose-sensors.yml
  src/docker-compose.yml
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/res/all-cpu.env
  src/res/all-dgpu.env
  src/res/all-gpu.env
  src/res/all-npu.env
  src/res/gst.env
  src/res/yolov5-cpu-class-gpu.env
  src/res/yolov5-gpu-class-cpu.env
  src/res/yolov5-gpu.env
Labels: enhancement

#685 bug: fix github actions build-pipeline-server failure
  Makefile
  src/pipeline-server/Dockerfile.pipeline-server
  src/pipeline-server/docker-compose.pipeline-server.yml
Labels: bug, oss_hackathon

#698 fix: update deprecated syntax in dlstreamer commands
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/res/all-cpu.env
  src/res/all-dgpu.env
  src/res/all-gpu.env
  src/res/all-npu.env
  src/res/yolov5-cpu-class-gpu.env
  src/res/yolov5-gpu-class-cpu.env
  src/res/yolov5-gpu.env
Labels: enhancement

#679 feat: use RTSP stream for output in headless displays
  helm/.env
  src/.env
  src/docker-compose.yml
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/pipelines/yolov5s_full.sh
Labels: enhancement, oss_hackathon
