Repository intel-retail/automated-self-checkout, pull requests merged in 2025-02, with the labels that each got.

#648 fix: Change pep8 to pycodestyle for fixing failure due to reviewdog GitHub action
  .github/.reviewdogConfig.yml
  .github/workflows/reviewdog.yaml
Labels: bug, Beginner, cicd

#636 bug: Legacy Issue Template Deprecated Resolves: #634
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, documentation, Beginner

#637 fix :RTSP stream | added sleep of 5 secs | Resolves: #633
  src/entrypoint.sh
Labels: bug, Beginner

#656 feat: Standardize the Environment settings between Docker Compose Files|add envs| Resolves: intel-retail#623
  helm/.env
  helm/docker-compose.yml
  src/.env
  src/docker-compose.yml
  src/pipeline-server/.env
  src/pipeline-server/docker-compose.pipeline-server.yml
Labels: enhancement, Beginner

#640 feat: Grafana dashboards for visualizing the sensor analytics
  src/retail-data-visualization/Dockerfile.grafana
  src/retail-data-visualization/Dockerfile.retail-data-visualization
  src/retail-data-visualization/Makefile
  src/retail-data-visualization/README.md
  src/retail-data-visualization/docker-compose.datavis.yml
  src/retail-data-visualization/dummy_data_load.py
  src/retail-data-visualization/grafana/dashboard.yaml
  src/retail-data-visualization/grafana/dashboards/dashboard.json
  src/retail-data-visualization/grafana/datasources/datasources.yaml
  src/retail-data-visualization/grafana/grafana.ini
  src/retail-data-visualization/requirements.txt
Labels: enhancement, Intermediate
